# Generated by Django 4.0.3 on 2022-06-26 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.FloatField()),
                ('statut_vaccinal', models.CharField(max_length=500)),
                ('sterilisation', models.BooleanField(default=b'I01\n')),
                ('image', models.ImageField(upload_to='media/')),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('animal', models.CharField(choices=[('Cat', 'CAT'), ('Dog', 'DOG'), ('Bird', 'BIRD')], max_length=4)),
                ('gender', models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
